### PR TITLE
Feature/safari support

### PR DESCRIPTION
**Pull request by aristidesstaffieri**
Adds fastlane support in order to deploy to Safari from an action in CI.

Adds:
- new action submitSafari(separate from submitProduction because we need to use a mac image for xcode
- fastlane integration
- safari store env vars

### CODE REVIEW

**Comment by aristidesstaffieri** [comment]
Should this be based from master? It's only build related so it seems ok to me but happy to target it for a release branch also.

**Comment by piyalbasu** [comment]
> Should this be based from master? It's only build related so it seems ok to me but happy to target it for a release branch also.

Yup, I think master makes sense. Do you want to double check the formatting changes? The line breaks seem a little off on some of them

**Review by piyalbasu — APPROVED** [review]

**Comment by aristidesstaffieri** [comment]
> > Should this be based from master? It's only build related so it seems ok to me but happy to target it for a release branch also.
> 
> Yup, I think master makes sense. Do you want to double check the formatting changes? The line breaks seem a little off on some of them

Hmm which line? I took it into the editor that parses it and it didn't complain, I don't visually see it yet 🤔

**Comment by aristidesstaffieri** [comment]
@piyalbasu we have the env vars set now, so once we are good here should I re-run the action and submit to the store for the first time?

**Review by piyalbasu — APPROVED** [review]

**Pull request merged**
